buildscript {
    repositories {
        google()  // Firebase requires this repository
        mavenCentral()  // For general dependencies
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.1'  // AGP version compatible with Flutter
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.22'  // Same version as in app level
        classpath 'com.google.gms:google-services:4.3.15'  // Ensure the version is correct
    }
}

allprojects {
    repositories {
        google()  // Firebase and Android dependencies
        mavenCentral()  // For libraries
        jcenter()  // Optional, for legacy libraries
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
